// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwtiuxequfzjjrnkjsyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3dGl1eGVxdWZ6ampybmtqc3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTQ5MTIsImV4cCI6MjA3MjY5MDkxMn0.jZSSJaol38__Td_uPsSXc-sCpZsY9n__7fRGhdiJXIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});